import type { BatchItem } from './types'
import dmImage from '../../assets/batches/digital-marketing.jpg'
import testingImage from '../../assets/batches/software-testing.jpg'
import analyticsImage from '../../assets/batches/data-analytics.jpg'
import sapImage from '../../assets/batches/sap.jpg'

export const CURRENT_BATCHES_DATA: BatchItem[] = [
  {
    id: 'digital-marketing',
    category: 'digital-marketing',
    title: 'Digital Marketing',
    shortTitle: 'Digital Marketing',
    image: dmImage,
    batchType: 'Weekday',
    startDate: 'Current',
    displayTime: '10:00 AM – 11:30 AM',
    modeDisplay: 'Classroom | Online',
    duration: '3 Months',
    displayLocation: 'Coimbatore - Saravanampatti & Gandhipuram',
    branches: [
      {
        name: 'Saravanampatti',
        landmark: 'Opp. CHIL SEZ IT Park',
        address: 'Saravanampatti Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
      {
        name: 'Gandhipuram',
        landmark: 'Opp. Cross Cut Road / Near Bus Stand',
        address: 'Gandhipuram Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
    ],
    slots: [
      {
        id: 'dm-regular',
        label: 'Regular Day',
        timeRange: '10:00 AM – 11:30 AM',
        days: 'Monday to Friday',
        seatsLeft: 3,
        totalSeats: 15,
        statusTag: 'Few Seats Left',
      },
      {
        id: 'dm-morning',
        label: 'Morning',
        timeRange: '07:30 AM – 09:30 AM',
        days: 'Monday to Friday',
        seatsLeft: 4,
        totalSeats: 15,
        statusTag: 'Filling Fast',
      },
      {
        id: 'dm-evening',
        label: 'Evening',
        timeRange: '06:30 PM – 08:30 PM',
        days: 'Monday to Friday',
        seatsLeft: 2,
        totalSeats: 15,
        statusTag: 'Almost Full',
      },
      {
        id: 'dm-weekend',
        label: 'Weekend',
        timeRange: '10:00 AM – 02:00 PM',
        days: 'Saturday & Sunday',
        seatsLeft: 5,
        totalSeats: 18,
        statusTag: 'Open',
      },
    ],
    keyHighlights: [
      'Live Google & Meta Ad budget testing with real ROI',
      'AI tools mastery: ChatGPT, Midjourney, Jasper & programmatic',
      'HubSpot, GA4 & Meta Blueprint Certifications',
    ],
    toolsCovered: ['Google Ads', 'Meta Ads', 'GA4', 'Semrush', 'HubSpot'],
    avgSalary: '₹4.5 - ₹10 LPA',
  },
  {
    id: 'software-testing',
    category: 'software-testing',
    title: 'Software Testing',
    shortTitle: 'Software Testing',
    image: testingImage,
    batchType: 'Weekday',
    startDate: 'Current',
    displayTime: '11:00 AM – 1:00 PM',
    modeDisplay: 'Classroom | Online',
    duration: '3 Months',
    displayLocation: 'Coimbatore - Saravanampatti & Gandhipuram',
    branches: [
      {
        name: 'Saravanampatti',
        landmark: 'Opp. CHIL SEZ IT Park',
        address: 'Saravanampatti Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
      {
        name: 'Gandhipuram',
        landmark: 'Near Central Bus Terminus',
        address: 'Gandhipuram Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
    ],
    slots: [
      {
        id: 'st-regular',
        label: 'Regular Day',
        timeRange: '11:00 AM – 1:00 PM',
        days: 'Monday to Friday',
        seatsLeft: 4,
        totalSeats: 16,
        statusTag: 'Filling Fast',
      },
      {
        id: 'st-morning',
        label: 'Morning',
        timeRange: '08:00 AM – 10:00 AM',
        days: 'Monday to Friday',
        seatsLeft: 3,
        totalSeats: 15,
        statusTag: 'Few Seats Left',
      },
      {
        id: 'st-evening',
        label: 'Evening',
        timeRange: '06:30 PM – 08:30 PM',
        days: 'Monday to Friday',
        seatsLeft: 2,
        totalSeats: 15,
        statusTag: 'Almost Full',
      },
      {
        id: 'st-weekend',
        label: 'Weekend',
        timeRange: '10:00 AM – 02:00 PM',
        days: 'Saturday & Sunday',
        seatsLeft: 5,
        totalSeats: 18,
        statusTag: 'Open',
      },
    ],
    keyHighlights: [
      'Manual QA + Selenium WebDriver & Playwright',
      'API testing with Postman & RestAssured with CI/CD',
      'Live Banking & E-Commerce project test frameworks',
    ],
    toolsCovered: ['Selenium', 'Playwright', 'Postman', 'Cypress', 'Jenkins'],
    avgSalary: '₹4.8 - ₹11 LPA',
  },
  {
    id: 'data-analytics',
    category: 'data-analytics',
    title: 'Data Analytics',
    shortTitle: 'Data Analytics',
    image: analyticsImage,
    batchType: 'Weekday',
    startDate: 'Current',
    displayTime: '12:00 PM – 2:30 PM',
    modeDisplay: 'Classroom | Online',
    duration: '3 Months',
    displayLocation: 'Coimbatore - Saravanampatti & Gandhipuram',
    branches: [
      {
        name: 'Saravanampatti',
        landmark: 'Opp. CHIL SEZ IT Park',
        address: 'Saravanampatti Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
      {
        name: 'Gandhipuram',
        landmark: 'Cross Cut Road Main Commercial Hub',
        address: 'Gandhipuram Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
    ],
    slots: [
      {
        id: 'da-regular',
        label: 'Regular Day',
        timeRange: '12:00 PM – 2:30 PM',
        days: 'Monday to Friday',
        seatsLeft: 2,
        totalSeats: 15,
        statusTag: 'Almost Full',
      },
      {
        id: 'da-morning',
        label: 'Morning',
        timeRange: '07:30 AM – 09:30 AM',
        days: 'Monday to Friday',
        seatsLeft: 4,
        totalSeats: 16,
        statusTag: 'Filling Fast',
      },
      {
        id: 'da-evening',
        label: 'Evening',
        timeRange: '07:00 PM – 09:00 PM',
        days: 'Monday to Friday',
        seatsLeft: 3,
        totalSeats: 15,
        statusTag: 'Few Seats Left',
      },
      {
        id: 'da-weekend',
        label: 'Weekend',
        timeRange: '09:00 AM – 01:00 PM',
        days: 'Saturday & Sunday',
        seatsLeft: 5,
        totalSeats: 18,
        statusTag: 'Open',
      },
    ],
    keyHighlights: [
      'Advanced SQL & Python Data Science (Pandas/NumPy)',
      'Executive Dashboards with Power BI & Tableau',
      'Real-world business case studies & portfolio prep',
    ],
    toolsCovered: ['Power BI', 'Python', 'SQL', 'Tableau', 'Excel DAX'],
    avgSalary: '₹5.0 - ₹13 LPA',
  },
  {
    id: 'sap',
    category: 'sap',
    title: 'SAP',
    shortTitle: 'SAP',
    image: sapImage,
    batchType: 'Weekday',
    startDate: 'Current',
    displayTime: '10:30 AM – 12:00 PM',
    modeDisplay: 'Classroom | Online',
    duration: '3 Months',
    displayLocation: 'Coimbatore - Saravanampatti & Gandhipuram',
    branches: [
      {
        name: 'Saravanampatti',
        landmark: 'Opp. CHIL SEZ IT Park',
        address: 'Saravanampatti Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
      {
        name: 'Gandhipuram',
        landmark: '7th Street Corner / Cross Cut Rd',
        address: 'Gandhipuram Campus, Coimbatore',
        modeAvailable: 'Classroom & Online',
        isOngoing: true,
      },
    ],
    slots: [
      {
        id: 'sap-regular',
        label: 'Regular Day',
        timeRange: '10:30 AM – 12:00 PM',
        days: 'Monday to Friday',
        seatsLeft: 3,
        totalSeats: 15,
        statusTag: 'Few Seats Left',
      },
      {
        id: 'sap-morning',
        label: 'Morning',
        timeRange: '07:30 AM – 09:30 AM',
        days: 'Monday to Friday',
        seatsLeft: 2,
        totalSeats: 14,
        statusTag: 'Almost Full',
      },
      {
        id: 'sap-evening',
        label: 'Evening',
        timeRange: '07:00 PM – 09:00 PM',
        days: 'Monday to Friday',
        seatsLeft: 4,
        totalSeats: 15,
        statusTag: 'Filling Fast',
      },
      {
        id: 'sap-weekend',
        label: 'Weekend',
        timeRange: '09:30 AM – 01:30 PM',
        days: 'Saturday & Sunday',
        seatsLeft: 4,
        totalSeats: 16,
        statusTag: 'Open',
      },
    ],
    keyHighlights: [
      'Dedicated 24/7 SAP S/4HANA & ECC server access',
      'SAP FICO, MM, SD, and HCM enterprise modules',
      'End-to-End configuration & live business cycle cases',
    ],
    toolsCovered: ['SAP S/4HANA', 'SAP GUI 8.0', 'SAP Fiori', 'Solution Manager'],
    avgSalary: '₹5.5 - ₹14 LPA',
  },
]
